name: 'clj-kondo checks'
description: 'Lint your clojure code with clj-kondo in parallel to your builds'
author: 'DeLaGuardo'
branding:
  icon: 'gift'
  color: 'blue'
inputs:
  clj-kondo-args:
    description: 'Arguments to be passed to clj-kondo'
    required: true
    default: '--lint src'
  check-name:
    description: 'Check name will be visible in Github Checks list'
    default: 'clj-kondo check'
  github_token:
    description: 'Github token to report linter results back to check'
    required: true
  levels:
    description: 'Annotate files in levels (e.g. "warning, error" or "error"), errors are always anotated, this is different from --fail-level clj-kondo param'
    default: 'info, warning, error'
  file-statuses:
    description: 'Annotate warnings as errors (and fail CI run) only in files which have following git statuses (e.g. "added, modified", or "removed, renamed"), leave blank to annotate all clj-kondo warnings as warnings, errors are always anotated'
    default: ''
  file-match:
    description: 'Annotate warnings as errors (and fail CI run) only in files with name matches the pattern (e.g. ".clj(c|s)?$"), leave blank to annotate all clj-kondo warnings as warnings, errors are always anotated'
    default: ''
  version:
    description: 'Specify version of clj-kondo Dockerfile to use'
    default: latest
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    CHECK_NAME: ${{ inputs.check-name }}
    LINT_ARGS: ${{ inputs.clj-kondo-args }}
    VERSION: ${{ inputs.version }}
    LEVELS: ${{ inputs.levels }}
    FILE_STATUSES: ${{ inputs.file-statuses }}
    FILE_MATCH: ${{ inputs.file-match }}
